### PR TITLE
Add password generator as builtin.password FQCN function

### PR DESCRIPTION
**Pull request by wiktor2200**
Hi! I think this fix for password generator should help
https://github.com/aalaesar/install_nextcloud/pull/136 and https://github.com/aalaesar/install_nextcloud/issues/137

### CODE REVIEW

**Comment by staticdev** [comment]
@wiktor2200 the error persists after this change.

**Comment by wiktor2200** [comment]
I see, maybe sth else has changed. Anyway if this generators will remain in the code there would be a need to apply these changes anyway, because it's using FQCN `ansible.builtin.password` function and without it will become deprecated sooner or later.

**Comment by staticdev** [comment]
@wiktor2200 I am adding the FQCN it in my PR, but the length is not necessary. We can use the default.

**Comment by wiktor2200** [comment]
Cool! :)

**Pull request closed without merging**
